import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SidebarComponent from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Road Surveillance App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row min-h-screen">
          <div className="flex flex-col min-w-80">
            <SidebarComponent />
          </div>
          <div className="flex flex-col w-full min-h-screen">{children}</div>
        </div>
      </body>
    </html>
  );
}
