import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutMiddleware from "./layout-middleware";
import SessionProvider from "./sessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Road Surveillance App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <LayoutMiddleware>{children}</LayoutMiddleware>
        </SessionProvider>
      </body>
    </html>
  );
}
